name: A2C

seed: 42
gamma : 0.99
learning_rate: 1e-4
max_episodes: 20000
max_steps_ep: 18000
features_encoding: mlp

network:
  features_encoding: mlp
  dimensions:
    - 512
    - 256
    - 128

epsilon:
  start: 1
  min: 0.1
  decay: 10000

replay_memory:
  enable: True
  batch_size : 64
  max_history: 1000000

target_network:
  enable: True
  freeze_interval: 1
  tau : 0.005
