name: A2C

seed: null
gamma : 0.99
learning_rate: 1e-4
max_episodes: 2
max_steps_ep: 2000
features_encoding: mlp

network:
  features_encoding: mlp
  dimensions:
    - 512
    - 256
    - 128

epsilon:
  start: 1
  min: 0.1
  decay: 1000

replay_memory:
  enable: True
  batch_size : 1
  max_history: 1

target_network:
  enable: True
  freeze_interval: 4
  tau : 0.005
