# Sapientino
name: OC

seed: null
temp: 1
gamma: 0.99
num_options: 8
update_frequency: 1
learning_rate: 1e-4
entropy_reg: 0.001 
termination_reg: 0.01 
max_episodes: 3000
max_steps_ep: 2000 

network:
  features_encoding: mlp
  dimensions:
    - 512
    - 256
    - 128

epsilon:
  start: 0.9
  min: 0.1
  decay: 10000
  optimal: 0.05 

replay_memory:
  enable: True
  batch_size: 64
  max_history: 1000000

target_network:
  enable: True
  freeze_interval: 4
  tau : 0.005

# Fourrooms
# name: OC
# seed : 42
# batch_size: 64 
# gamma: 0.99
# epsilon_start: 0.1
# epsilon_min: 0.1
# epsilon_decay: 1000
# num_options: 8
# learning_rate: 1e-4
# max_episodes: 1500
# max_steps_ep: 2000 
# entropy_reg: 0.01 
# freeze_interval: 400 
# max_history: 1000000
# optimal_eps: 0.05 
# temp: 1
# termination_reg: 0.01 
# update_frequency: 4
# features_encoding: null