# name: OC
# seed : 42
# batch_size: 64
# gamma: 0.99
# epsilon_start: 0.9
# epsilon_min: 0.1
# epsilon_decay: 200000
# num_options: 8
# learning_rate: 1e-4
# max_episodes: 5000
# max_steps_ep: 18000  
# entropy_reg: 0.001 
# freeze_interval: 200
# max_history: 100000
# optimal_eps: 0.05 
# temp: 1
# termination_reg: 0.01 
# update_frequency: 4
# features_encoding: mlp

# Fourrooms
name: OC
seed : 42
batch_size: 240 
gamma: 0.999
epsilon_start: 1.0
epsilon_min: 0.1
epsilon_decay: 100000
num_options: 1
learning_rate: 1e-4
max_episodes: 3000
max_steps_ep: 1000 
entropy_reg: 0.01 
freeze_interval: 400 #10000 
max_history: 1000000
optimal_eps: 0.05 
temp: 1
termination_reg: 0.01 
update_frequency: 4
features_encoding: null