# Sapientino
name: PPO

seed: 42
gamma: 0.99
lr_actor: 0.0003 
lr_critic: 0.001
has_continuous_action_space: False
max_episodes: 3000000
max_steps_ep: 350 
eps_clip: 0.2 

K_epochs: 80 

action_std:
  init: 0.6
  decay_rate: 0.05 
  min: 0.1        
  decay_freq: 2.5e5