experiment: 0
logger:
  folder_path: runs
  wandb_project: HRL
model:
  path: models
  load_model: null
defaults:
  - env: fourrooms
  - agent: option_critic
  - _self_

hydra:
  sweeper:
    params:
      experiment: range(50)