hydra:
  launcher:
    n_jobs: 2
  sweeper:
    params:
      experiment: range(1, 11)

experiment: 1
note: null
replicate_experiment: null
logger:
  type: base  # base - tensorboard - wandb
  folder_path: logs
  wandb_project: HRL
  log_step: False
  log_episode: True
  log_terminal: True

model:
  path: models
  load_model: null

# env:
#   name: Taxi-v3

defaults:
  - env: sapientino
  - agent: oc
  - override hydra/launcher: joblib
  - _self_

