hydra:
  launcher:
    n_jobs: 3
  sweeper:
    params:
      experiment: range(1, 50)

experiment: 1
logger:
  type: tensorboard
  folder_path: logs
  wandb_project: HRL
model:
  path: models
  load_model: null
defaults:
  - env: sapientino
  - agent: oc
  - override hydra/launcher: joblib
  - _self_

