hydra:
  launcher:
    n_jobs: 4
  sweeper:
    params:
      experiment: range(1, 50)

experiment: 1
note: three_layer
logger:
  type: wandb
  folder_path: logs
  wandb_project: HRL
  log_step: False
  log_episode: True

model:
  path: models
  load_model: null

defaults:
  - env: sapientino
  - agent: oc
  - override hydra/launcher: joblib
  - _self_

