hydra:
  launcher:
    n_jobs: 5
  sweeper:
    params:
      experiment: range(1, 50)

experiment: 1
logger:
  type: wandb
  folder_path: logs
  wandb_project: HRL
model:
  path: models
  load_model: null
defaults:
  - env: sapientino
  - agent: sarsa
  - override hydra/launcher: joblib
  - _self_  
  
