hydra:
  launcher:
    n_jobs: 4
  sweeper:
    params:
      experiment: range(1, 20)

experiment: 1
note: null
logger:
  type: tensorboard
  folder_path: logs
  wandb_project: HRL
  log_step: False
  log_episode: True
  log_terminal: True

model:
  path: models
  load_model: null

defaults:
  - env: sapientino
  - agent: tabular_sarsa
  - override hydra/launcher: joblib
  - _self_

